### PR TITLE
Replaced Logging System

### PR DESCRIPTION
**Pull request by Valkryst**
I couldn't leave the project with the abomination of a Logging System that I created way back, so I've updated everything to work with the latest version of it. You can find the code for Logger within the Utilities project on my github page.

If you go through the entire project and add TODO comments with instructions on what you would like done, then I won't mind continuing work on the project.

### CODE REVIEW

**Comment by marijnz** [comment]
Hey, will merge it. But, I believe it should be log(logtype, log), makes more sense to give context to the log before the log itself, perhaps this is personal experience / preference, what's your view on this? I also see you added LOG_TYPE to the enum types, isn't this a little redundant, as the enum name itself contains this already?

And I will do that! Will add the TODO's in a next commit, any of these days.

**Comment by Valkryst** [comment]
Ah. The LOG_TYPE enum should have bern deleted. The Logger class contains three static variables instead.

I normally wouldn't use statics, but this situation seemed as if it would work well with them. The Logger can be called at any time and doesn't rely on the enum anymore.

Hmm... I'd consider the ordering to be a preference. Go ahead and grab my code from the Utilities repo and modify it however you'd like. I'm just used to doing it this way. =P





Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Marijn Zwemmer <notifications@github.com> </div><div>Date:02/01/2015  5:59 PM  (GMT-04:00) </div><div>To: marijnz/BunnyEmu <BunnyEmu@noreply.github.com> </div><div>Cc: Valkryst <valkryst@valkryst.com> </div><div>Subject: Re: [BunnyEmu] Replaced Logging System (#16) </div><div>
</div>Hey, will merge it. But, I believe it should be log(logtype, log), makes more sense to give context to the log before the log itself, perhaps this is personal experience / preference, what's your view on this? I also see you added LOG_TYPE to the enum types, isn't this a little redundant, as the enum name itself contains this already?

And I will do that! Will add the TODO's in a next commit, any of these days.

**Comment by marijnz** [comment]
Ok, so where did the actual Logger class go? The current code is not working.

**Comment by Valkryst** [comment]
It's within tge Utilities.jar file in the libs directory IIRC.


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Marijn Zwemmer <notifications@github.com> </div><div>Date:03/01/2015  1:43 PM  (GMT-04:00) </div><div>To: marijnz/BunnyEmu <BunnyEmu@noreply.github.com> </div><div>Cc: Valkryst <valkryst@valkryst.com> </div><div>Subject: Re: [BunnyEmu] Replaced Logging System (#16) </div><div>
</div>Ok, so where did the actual Logger class go? The current code is not working.

**Comment by marijnz** [comment]
Ok, I saw it and immediately forgot about it, stupid me. What's the reason for this library, where is it from?

**Comment by Valkryst** [comment]
It's just the compiled form of my Utilities repo. It holds the Logger class.


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Marijn Zwemmer <notifications@github.com> </div><div>Date:03/01/2015  2:53 PM  (GMT-04:00) </div><div>To: marijnz/BunnyEmu <BunnyEmu@noreply.github.com> </div><div>Cc: Valkryst <valkryst@valkryst.com> </div><div>Subject: Re: [BunnyEmu] Replaced Logging System (#16) </div><div>
</div>Ok, I saw it and immediately forgot about it, stupid me. What's the reason for this library, where is it from?

**Comment by marijnz** [comment]
Ok, added the todo's: https://github.com/marijnz/BunnyEmu/commit/703afb7252f18ad0773870ca8106936c99cf0d76

**Comment by Valkryst** [comment]
Alright, I'll take a look into how those packets work in a few days.

**Pull request merged**
